version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dadinos
      POSTGRES_DB: forgocrud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-crud-app
    ports:
      - "8040:8040"
    depends_on:
      - db
    volumes:
      - .:/root
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
