name: Github Action Build GO First App Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build docker image
      run: docker build -t abdiaoo/first-go-crud:latest .

    - name: List docker images
      run: docker images
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push image to Docker Hub
      run: docker push abdiaoo/first-go-crud:latest
    
    - name: Logout from Docker Hub
      run: docker logout
